
 server {
        # Nginx listens on port 80 INSIDE the container
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;


        # Send all requests at "/" to the frontend
        location / {
      
            try_files $uri $uri/ /index.html;
        }
 }
